### PR TITLE
Frontend improvements

### PR DESCRIPTION
**Pull request by RRorg**
- increased Favicon compatibility
- optional HD Favicon added
- Windows8 Tiles compressed
- Canonical tag added
- Apple Touch Icons added
- Facebook OG Tags added

### CODE REVIEW

**Comment by wdamien** [comment]
Thanks for the pull request!  I would love to accept it, however, all of your new images are invalid png's.  If you can push valid versions I'll be happy to accept this.

**Comment by RRorg** [comment]
Github seems to be messing with PNG files - when I download the original repo, the PNGs are invalid too. I'm not sure what is causing this, or how to fix it. Well, I sent the whole package as a ZIP to the GSkinner info mail, maybe you can help us out here!

**Comment by wdamien** [comment]
Manually merged, via: https://github.com/gskinner/regexr/commit/0fcbcffcad7038838aebc45298e28f984ea4e3b5

**Comment by gskinner** [comment]
Thanks for the pull request - it's always great to have users contributing!

**Pull request closed without merging**
